config/routes.rb
Rails.application.routes.draw do
  get 'page/homepage'
  get 'manga/index'
  get 'manga/read'

  resources :categories
  resources :authors

  root 'page#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :mangas, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :mangas, dependent: :destroy

  validates :name, presence: :true,  uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :mangas

  validates :email, presence: true
  validates :detail, presence: true
end

app/models/manga.rb
class Manga < ApplicationRecord
  belongs_to :author
  belongs_to :category
  has_many :comments, dependent: :destroy
  paginates_per 2

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @author = Author.all.page(params[:page]).per(4)
  end

  def new
  end

  def create
    @author = Author.new(author_params)
    @author.save
    redirect_to authors_path
  end
  
  def destroy
    @author = Author.find(params[:id])
    @author.destroy
 
    redirect_to authors_path
  end

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
 
    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/manga_controller.rb
class MangaController < ApplicationController
  def index
  end

  def read
    @manga = Manga.all.page(params[:page]).per(1)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def homepage
    @mangas = Manga.all.page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/cotegory_helper.rb
module CotegoryHelper
end

app/helpers/manga_helper.rb
module MangaHelper
end

app/helpers/page_controller_helper.rb
module PageControllerHelper
end

app/views/authors/index.html.erb
  <%= render "partials/header" %>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">Author List</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                    <div class="btn btn-dark">
                    <%= link_to  "New author", new_author_path %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th><em class="fa fa-cog"></em></th>
                        <th class="hidden-xs">ID</th>                       <th>Name</th>
                    </tr> 
                   </thead>
                        <tbody>
                        <% @author.each do |author| %>
                          <tr>
                            <td align="center">
                              <div class="btn btn-danger"><em class="fa fa-trash"></em>
                                <%= link_to  "Delete", author_path(author),
                                method: :delete, data: {confirm: "Are you sure?"} %>
                              </div>
                            </td>
                            <td class="hidden-xs"><%= author.id %></td>
                            <td><%= author.name %></td>
                          </tr>
                        <% end %>  
                        </tbody>
                </table>

                <div class="pagination justify-content-center"><%= paginate @author %></div>
              </div>
</div></div></div>

app/views/authors/new.html.erb
 <%= render  "partials/header" %>

 <div class="content">
    <h1> New Author </h1>
    <%= form_with scope: :author, url: authors_path, class: "form", local: true do |form| %>
  
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <%= form.submit  "Save" %>
    <% end %>

    <%= link_to "", authors_path %>
</div>

app/views/categories/index.html.erb
  <%= render "partials/header" %>


  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">Category</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                    <div class="btn btn-dark">
                    <%= link_to  "New Category", new_category_path %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th><em class="fa fa-cog"></em></th>
                        <th class="hidden-xs">ID</th>                       <th>Name</th>
                    </tr> 
                   </thead>
                        <tbody>
                        <% @category.each do |category| %>
                          <tr>
                            <td align="center">
                              <div class="btn btn-danger"><em class="fa fa-trash"></em>
                                <%= link_to  "Delete", category_path(category),
                                method: :delete, data: {confirm: "Are you sure?"} %>
                              </div>
                            </td>
                            <td class="hidden-xs"><%= category.id %></td>
                            <td><%= category.name %></td>
                          </tr>
                        <% end %>  
                        </tbody>
                </table>
              </div>
</div></div></div>

app/views/categories/new.html.erb
 <%= render  "partials/header" %>
 
 <div class="content">
    <h1> New Category </h1>
    <%= form_with scope: :category, url: categories_path, class: "form", local: true do |form| %>
  
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <%= form.submit  "Save" %>
    <% end %>

    <%= link_to "", categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogtruyen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield  %>
  </body>
</html>

app/views/manga/index.html.erb
<%= render "partials/header" %>
  
<div class="container">
<h1 class="my-4">Chapter List</h1>
<%= link_to  "Chap1", controller: "manga", action: "read" %>

app/views/manga/read.html.erb
<%= render "partials/header" %>

<div class="background">
  <div class="read">
    <% @manga.first(10).each do |manga| %>
    <%= image_tag  "chapter.jpg" %>
    <br>
    <% end %>
  </div>

  <div class="pagination justify-content-center"><%= paginate @manga %></div>
</div>

app/views/page/homepage.html.erb
<!-- Header -->
<%= render "partials/header" %>

<!-- Manga List -->
<div class="container">
<h1 class="my-4">Manga List</h1>
<% @mangas.each do |manga| %>
<div class="row">
  <div class="col-md-7">
    <a href="#">
      <%= image_tag(manga.img_path, size: "600x300") %>
    </a>
  </div>
  <div class="col-md-5">
    <h3><%= manga.name %></h3>
    <h5>Author: <%= manga.author.name %></h5>
    <h6>Category: <%= manga.category.name %></h6>
    <p><%= manga.summary %></p>
    <div class="btn btn-dark">
      <%= link_to  "Read more", controller: "manga", action: "index" %>
    </div>
  </div>
</div>
<hr>
<% end %>

<!-- Pagination -->
<div class="pagination justify-content-center"><%= paginate @mangas %></div>

<!-- Footer -->
<%= render "partials/footer" %>

app/views/partials/_footer.html.erb
<footer class="footer-background">
  <div class="container">
    <p class="m-0 text-center text-white">Design by me</p>
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand"><%= link_to  "Blogmanga", controller: "page",action: "homepage", class: "btn btn-primary" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <div class="nav-link"><%= link_to  "Category", controller: "categories",
          action: "index", class: "btn btn-primary" %>
          </div>
        </li>
        <li class="nav-item active">
          <div class="nav-link"><%= link_to  "Author", controller: "authors", action: "index" %></div>
        </li>
      </ul>
    </div>
  </div>
</nav>